elasticsearch:
  image: elasticsearch:1.7
#  ports:
#    - "29200:9200"
  volumes:
    - ./volumes/elasticsearch:/usr/share/elasticsearch/data
  command: elasticsearch -Des.cluster.name="lac" -Des.discovery.zen.ping.multicast.enabled=false
urlshortener:
  build: urlshortener/
  volumes:
    - ./var:/app/var
  ports:
    - 127.0.0.1:5005:5000
lac:
  build: .
  stdin_open: true
  tty: true
  environment:
    - ENV=development
    - SECRET=mybigsecret
    - APPLICATION_URL=http://local.ecreall.com:8080
    - MAIL_DEFAULT_SENDER=contact@example.com
    - TIMEOUT=999999999
    - POSTFIX_HOST=172.17.0.1
    - POSTFIX_PORT=9025
    - WORKERS=1
    - ELASTICSEARCH_PORT=elasticsearch:9200
    - ARANGO_PORT=arango:8529
    - ARANGO_ROOT_PASSWORD=very_secret
  ports:
   - "5000:5000"
   - "5001:5001"
  links:
    - elasticsearch:elasticsearch
    - arango:arango
  volumes:
    - ./var:/app/var
    - ./etc/varnish.vcl:/app/etc/varnish.vcl:ro
    - ./lac:/app/lac
    - ./cache:/app/cache
nginx:
  image: nginx
  environment:
    LOGSPOUT: ignore
  volumes:
    - ./nginx-app-dev.conf:/etc/nginx/conf.d/app.conf:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./html:/etc/nginx/html:ro
    - ./tls:/etc/nginx/tls:ro
  ports:
    - "8080:80"
    - "8443:443"
  links:
    - lac:app
    - urlshortener:urlshortener
arango:
  image: arangodb
  environment:
    - ARANGO_ROOT_PASSWORD=very_secret
  volumes:
    - ./volumes/arangodb:/var/lib/arangodb
    - ./volumes/arangodb-apps:/var/lib/arangodb-apps
