elasticsearch:
  restart: always
  image: elasticsearch:2.3
  volumes:
    - ./volumes/elasticsearch:/usr/share/elasticsearch/data
  command: elasticsearch -Des.cluster.name="lac" -Des.node.name=node1 -Des.discovery.zen.ping.multicast.enabled=false
urlshortener:
  restart: always
  build: urlshortener/
  volumes:
    - ./var:/app/var
lac:
  restart: always
  build: .
  environment:
    - SECRET=mybigsecret
    - APPLICATION_URL=https://www.lagendacommun.org
    - MAIL_DEFAULT_SENDER=noreply@example.com
    - TIMEOUT=600
    - WORKERS=2
    - ELASTICSEARCH_PORT=elasticsearch:9200
    - ARANGO_PORT=arango:8529
    - ARANGO_ROOT_PASSWORD=very_secret
  ports:
    - "127.0.0.1:5000:5000"
  links:
    - elasticsearch:elasticsearch
    - arango:arango
  volumes:
    - ./var:/app/var
    - ./etc/varnish.vcl:/app/etc/varnish.vcl:ro
  external_links:
    - postfix:mail
nginx:
  restart: always
  image: undownding/nginx-http2
  environment:
    LOGSPOUT: ignore
  volumes:
    - ./nginx-app-prod.conf:/etc/nginx/conf.d/app.conf:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - ./html:/etc/nginx/html:ro
    - ./tls:/etc/nginx/tls:ro
  ports:
    - "80:80"
    - "443:443"
  links:
    - lac:app
    - urlshortener:urlshortener
arango:
  image: arangodb
  environment:
    - ARANGO_ROOT_PASSWORD=very_secret
  volumes:
    - ./volumes/arangodb:/var/lib/arangodb
    - ./volumes/arangodb-apps:/var/lib/arangodb-apps
